# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:
date_format: "ordinal"
title: 孤寂流年
subtitle: "深刻反思，改过自新"
description: "孤寂流年的个人博客"
keywords: 孤寂流年, tyzy313481929
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: XinLei Feng
organization: blog.fyiyao.com
organization_url: blog.fyiyao.com
github_username: tyzy313481929
location: ZhengZhou, China
email: tyzy313481929@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于
    
  -
    href: http://beian.miit.gov.cn
    label: 豫ICP备17037980号-1

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: tyzy313481929
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: tyzy313481929
    repo: blog-comments
    oauth:
        client_id: 7720c49ea6548ae39380
        client_secret: 8818b246d204aa40e4a07335be6a90d59f6e286d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
